language: node_js

node_js:
  - 'node'
  - '11'
  - '12'

branches:
  only:
  - /.*/


install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - mkdir ./test/compile-time/actual-output
  - npm run sanity-check-travis
  - npm install codecov

after_success:
  - ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
