import * as tm from "type-mapping/fluent";
import * as tsql from "../../../../../../dist";

const myTable = tsql.table("myTable")
    .addColumns({
        someColumnA : tm.mysql.double(),
        someColumnB : tm.mysql.double(),
        someColumnC : tm.mysql.double(),
    });

export const expr = tsql.double.atan2(
    tsql.double.atan2(
        tsql.double.atan2(
            tsql.double.atan2(
                tsql.double.atan2(
                    tsql.double.atan2(
                        tsql.double.atan2(
                            tsql.double.atan2(
                                tsql.double.atan2(
                                    tsql.double.atan2(
                                        tsql.double.atan2(
                                            tsql.double.atan2(
                                                tsql.double.atan2(
                                                    tsql.double.atan2(
                                                        tsql.double.atan2(
                                                            tsql.double.atan2(
                                                                tsql.double.atan2(
                                                                    tsql.double.atan2(
                                                                        tsql.double.atan2(
                                                                            tsql.double.atan2(
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                            ),
                                                                            myTable.columns.someColumnC
                                                                        ),
                                                                        myTable.columns.someColumnC
                                                                    ),
                                                                    myTable.columns.someColumnC
                                                                ),
                                                                myTable.columns.someColumnC
                                                            ),
                                                            myTable.columns.someColumnC
                                                        ),
                                                        myTable.columns.someColumnC
                                                    ),
                                                    myTable.columns.someColumnC
                                                ),
                                                myTable.columns.someColumnC
                                            ),
                                            myTable.columns.someColumnC
                                        ),
                                        myTable.columns.someColumnC
                                    ),
                                    myTable.columns.someColumnC
                                ),
                                myTable.columns.someColumnC
                            ),
                            myTable.columns.someColumnC
                        ),
                        myTable.columns.someColumnC
                    ),
                    myTable.columns.someColumnC
                ),
                myTable.columns.someColumnC
            ),
            myTable.columns.someColumnC
        ),
        myTable.columns.someColumnC
    ),
    myTable.columns.someColumnC
);

export const expr2 = tsql.double.atan2(
    tsql.double.atan2(
        tsql.double.atan2(
            tsql.double.atan2(
                tsql.double.atan2(
                    tsql.double.atan2(
                        tsql.double.atan2(
                            tsql.double.atan2(
                                tsql.double.atan2(
                                    tsql.double.atan2(
                                        tsql.double.atan2(
                                            tsql.double.atan2(
                                                tsql.double.atan2(
                                                    tsql.double.atan2(
                                                        tsql.double.atan2(
                                                            tsql.double.atan2(
                                                                tsql.double.atan2(
                                                                    tsql.double.atan2(
                                                                        tsql.double.atan2(
                                                                            tsql.double.atan2(
                                                                                expr,
                                                                                myTable.columns.someColumnA,
                                                                            ),
                                                                            myTable.columns.someColumnB
                                                                        ),
                                                                        myTable.columns.someColumnC
                                                                    ),
                                                                    myTable.columns.someColumnA
                                                                ),
                                                                myTable.columns.someColumnB
                                                            ),
                                                            myTable.columns.someColumnC
                                                        ),
                                                        myTable.columns.someColumnA
                                                    ),
                                                    myTable.columns.someColumnB
                                                ),
                                                myTable.columns.someColumnC
                                            ),
                                            myTable.columns.someColumnA
                                        ),
                                        myTable.columns.someColumnB
                                    ),
                                    myTable.columns.someColumnC
                                ),
                                myTable.columns.someColumnA
                            ),
                            myTable.columns.someColumnB
                        ),
                        myTable.columns.someColumnC
                    ),
                    myTable.columns.someColumnA
                ),
                myTable.columns.someColumnB
            ),
            myTable.columns.someColumnC
        ),
        myTable.columns.someColumnA
    ),
    myTable.columns.someColumnB
);

export const expr3 = tsql.double.atan2(
    tsql.double.atan2(
        tsql.double.atan2(
            tsql.double.atan2(
                tsql.double.atan2(
                    tsql.double.atan2(
                        tsql.double.atan2(
                            tsql.double.atan2(
                                tsql.double.atan2(
                                    tsql.double.atan2(
                                        tsql.double.atan2(
                                            tsql.double.atan2(
                                                tsql.double.atan2(
                                                    tsql.double.atan2(
                                                        tsql.double.atan2(
                                                            tsql.double.atan2(
                                                                tsql.double.atan2(
                                                                    tsql.double.atan2(
                                                                        tsql.double.atan2(
                                                                            tsql.double.atan2(
                                                                                expr2,
                                                                                myTable.columns.someColumnA,
                                                                            ),
                                                                            myTable.columns.someColumnB
                                                                        ),
                                                                        myTable.columns.someColumnC
                                                                    ),
                                                                    myTable.columns.someColumnA
                                                                ),
                                                                myTable.columns.someColumnB
                                                            ),
                                                            myTable.columns.someColumnC
                                                        ),
                                                        myTable.columns.someColumnA
                                                    ),
                                                    myTable.columns.someColumnB
                                                ),
                                                myTable.columns.someColumnC
                                            ),
                                            myTable.columns.someColumnA
                                        ),
                                        myTable.columns.someColumnB
                                    ),
                                    myTable.columns.someColumnC
                                ),
                                myTable.columns.someColumnA
                            ),
                            myTable.columns.someColumnB
                        ),
                        myTable.columns.someColumnC
                    ),
                    myTable.columns.someColumnA
                ),
                myTable.columns.someColumnB
            ),
            myTable.columns.someColumnC
        ),
        myTable.columns.someColumnA
    ),
    myTable.columns.someColumnB
);

export const expr4 = tsql.double.atan2(
    tsql.double.atan2(
        tsql.double.atan2(
            tsql.double.atan2(
                tsql.double.atan2(
                    tsql.double.atan2(
                        tsql.double.atan2(
                            tsql.double.atan2(
                                tsql.double.atan2(
                                    tsql.double.atan2(
                                        tsql.double.atan2(
                                            tsql.double.atan2(
                                                tsql.double.atan2(
                                                    tsql.double.atan2(
                                                        tsql.double.atan2(
                                                            tsql.double.atan2(
                                                                tsql.double.atan2(
                                                                    tsql.double.atan2(
                                                                        tsql.double.atan2(
                                                                            tsql.double.atan2(
                                                                                expr3,
                                                                                myTable.columns.someColumnA,
                                                                            ),
                                                                            myTable.columns.someColumnB
                                                                        ),
                                                                        myTable.columns.someColumnC
                                                                    ),
                                                                    myTable.columns.someColumnA
                                                                ),
                                                                myTable.columns.someColumnB
                                                            ),
                                                            myTable.columns.someColumnC
                                                        ),
                                                        myTable.columns.someColumnA
                                                    ),
                                                    myTable.columns.someColumnB
                                                ),
                                                myTable.columns.someColumnC
                                            ),
                                            myTable.columns.someColumnA
                                        ),
                                        myTable.columns.someColumnB
                                    ),
                                    myTable.columns.someColumnC
                                ),
                                myTable.columns.someColumnA
                            ),
                            myTable.columns.someColumnB
                        ),
                        myTable.columns.someColumnC
                    ),
                    myTable.columns.someColumnA
                ),
                myTable.columns.someColumnB
            ),
            myTable.columns.someColumnC
        ),
        myTable.columns.someColumnA
    ),
    myTable.columns.someColumnB
);

export const expr5 = tsql.double.atan2(
    tsql.double.atan2(
        tsql.double.atan2(
            tsql.double.atan2(
                tsql.double.atan2(
                    tsql.double.atan2(
                        tsql.double.atan2(
                            tsql.double.atan2(
                                tsql.double.atan2(
                                    tsql.double.atan2(
                                        tsql.double.atan2(
                                            tsql.double.atan2(
                                                tsql.double.atan2(
                                                    tsql.double.atan2(
                                                        tsql.double.atan2(
                                                            tsql.double.atan2(
                                                                tsql.double.atan2(
                                                                    tsql.double.atan2(
                                                                        tsql.double.atan2(
                                                                            tsql.double.atan2(
                                                                                expr4,
                                                                                myTable.columns.someColumnA,
                                                                            ),
                                                                            myTable.columns.someColumnB
                                                                        ),
                                                                        myTable.columns.someColumnC
                                                                    ),
                                                                    myTable.columns.someColumnA
                                                                ),
                                                                myTable.columns.someColumnB
                                                            ),
                                                            myTable.columns.someColumnC
                                                        ),
                                                        myTable.columns.someColumnA
                                                    ),
                                                    myTable.columns.someColumnB
                                                ),
                                                myTable.columns.someColumnC
                                            ),
                                            myTable.columns.someColumnA
                                        ),
                                        myTable.columns.someColumnB
                                    ),
                                    myTable.columns.someColumnC
                                ),
                                myTable.columns.someColumnA
                            ),
                            myTable.columns.someColumnB
                        ),
                        myTable.columns.someColumnC
                    ),
                    myTable.columns.someColumnA
                ),
                myTable.columns.someColumnB
            ),
            myTable.columns.someColumnC
        ),
        myTable.columns.someColumnA
    ),
    myTable.columns.someColumnB
);
