import * as tsql from "../../../../../../../dist";

export const expr = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        tsql.and(
                                                                                                                            tsql.and(
                                                                                                                                tsql.and(
                                                                                                                                    tsql.and(
                                                                                                                                        tsql.and(
                                                                                                                                            tsql.and(
                                                                                                                                                tsql.and(
                                                                                                                                                    tsql.and(
                                                                                                                                                    )
                                                                                                                                                )
                                                                                                                                            )
                                                                                                                                        )
                                                                                                                                    )
                                                                                                                                )
                                                                                                                            )
                                                                                                                        )
                                                                                                                    )
                                                                                                                )
                                                                                                            )
                                                                                                        )
                                                                                                    )
                                                                                                )
                                                                                            )
                                                                                        )
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);
export const expr2 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        tsql.and(
                                                                                                                            tsql.and(
                                                                                                                                tsql.and(
                                                                                                                                    tsql.and(
                                                                                                                                        tsql.and(
                                                                                                                                            tsql.and(
                                                                                                                                                tsql.and(
                                                                                                                                                    tsql.and(
                                                                                                                                                        expr
                                                                                                                                                    )
                                                                                                                                                )
                                                                                                                                            )
                                                                                                                                        )
                                                                                                                                    )
                                                                                                                                )
                                                                                                                            )
                                                                                                                        )
                                                                                                                    )
                                                                                                                )
                                                                                                            )
                                                                                                        )
                                                                                                    )
                                                                                                )
                                                                                            )
                                                                                        )
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);
export const expr3 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        tsql.and(
                                                                                                                            tsql.and(
                                                                                                                                tsql.and(
                                                                                                                                    tsql.and(
                                                                                                                                        tsql.and(
                                                                                                                                            tsql.and(
                                                                                                                                                tsql.and(
                                                                                                                                                    tsql.and(
                                                                                                                                                        expr2
                                                                                                                                                    )
                                                                                                                                                )
                                                                                                                                            )
                                                                                                                                        )
                                                                                                                                    )
                                                                                                                                )
                                                                                                                            )
                                                                                                                        )
                                                                                                                    )
                                                                                                                )
                                                                                                            )
                                                                                                        )
                                                                                                    )
                                                                                                )
                                                                                            )
                                                                                        )
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);
/**
 * No more errors after 100+ calls.
 * This is good.
 */
tsql.and(expr3);
