import * as tsql from "../../../../../../../dist";

export const expr = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        tsql.and(
                                                                                                                            tsql.and(
                                                                                                                                tsql.and(
                                                                                                                                    tsql.and(
                                                                                                                                        tsql.and(
                                                                                                                                            tsql.and(
                                                                                                                                                tsql.and(
                                                                                                                                                    tsql.and(
                                                                                                                                                    )
                                                                                                                                                )
                                                                                                                                            )
                                                                                                                                        )
                                                                                                                                    )
                                                                                                                                )
                                                                                                                            )
                                                                                                                        )
                                                                                                                    )
                                                                                                                )
                                                                                                            )
                                                                                                        )
                                                                                                    )
                                                                                                )
                                                                                            )
                                                                                        )
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);
tsql.and(expr);
