import * as tsql from "../../../../../../../dist";

export const expr = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and().as("x")
                                                                                                                ).as("x")
                                                                                                            ).as("x")
                                                                                                        ).as("x")
                                                                                                    ).as("x")
                                                                                                ).as("x")
                                                                                            ).as("x")
                                                                                        ).as("x")
                                                                                    ).as("x")
                                                                                ).as("x")
                                                                            ).as("x")
                                                                        ).as("x")
                                                                    ).as("x")
                                                                ).as("x")
                                                            ).as("x")
                                                        ).as("x")
                                                    ).as("x")
                                                ).as("x")
                                            ).as("x")
                                        ).as("x")
                                    ).as("x")
                                ).as("x")
                            ).as("x")
                        ).as("x")
                    ).as("x")
                ).as("x")
            ).as("x")
        ).as("x")
    ).as("x")
).as("x");
export const expr2 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        expr
                                                                                                                    ).as("x")
                                                                                                                ).as("x")
                                                                                                            ).as("x")
                                                                                                        ).as("x")
                                                                                                    ).as("x")
                                                                                                ).as("x")
                                                                                            ).as("x")
                                                                                        ).as("x")
                                                                                    ).as("x")
                                                                                ).as("x")
                                                                            ).as("x")
                                                                        ).as("x")
                                                                    ).as("x")
                                                                ).as("x")
                                                            ).as("x")
                                                        ).as("x")
                                                    ).as("x")
                                                ).as("x")
                                            ).as("x")
                                        ).as("x")
                                    ).as("x")
                                ).as("x")
                            ).as("x")
                        ).as("x")
                    ).as("x")
                ).as("x")
            ).as("x")
        ).as("x")
    ).as("x")
).as("x");

export const expr3 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        expr2
                                                                                                                    ).as("x")
                                                                                                                ).as("x")
                                                                                                            ).as("x")
                                                                                                        ).as("x")
                                                                                                    ).as("x")
                                                                                                ).as("x")
                                                                                            ).as("x")
                                                                                        ).as("x")
                                                                                    ).as("x")
                                                                                ).as("x")
                                                                            ).as("x")
                                                                        ).as("x")
                                                                    ).as("x")
                                                                ).as("x")
                                                            ).as("x")
                                                        ).as("x")
                                                    ).as("x")
                                                ).as("x")
                                            ).as("x")
                                        ).as("x")
                                    ).as("x")
                                ).as("x")
                            ).as("x")
                        ).as("x")
                    ).as("x")
                ).as("x")
            ).as("x")
        ).as("x")
    ).as("x")
).as("x");

export const expr4 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        tsql.and(
                                                                                            tsql.and(
                                                                                                tsql.and(
                                                                                                    tsql.and(
                                                                                                        tsql.and(
                                                                                                            tsql.and(
                                                                                                                tsql.and(
                                                                                                                    tsql.and(
                                                                                                                        expr3
                                                                                                                    ).as("x")
                                                                                                                ).as("x")
                                                                                                            ).as("x")
                                                                                                        ).as("x")
                                                                                                    ).as("x")
                                                                                                ).as("x")
                                                                                            ).as("x")
                                                                                        ).as("x")
                                                                                    ).as("x")
                                                                                ).as("x")
                                                                            ).as("x")
                                                                        ).as("x")
                                                                    ).as("x")
                                                                ).as("x")
                                                            ).as("x")
                                                        ).as("x")
                                                    ).as("x")
                                                ).as("x")
                                            ).as("x")
                                        ).as("x")
                                    ).as("x")
                                ).as("x")
                            ).as("x")
                        ).as("x")
                    ).as("x")
                ).as("x")
            ).as("x")
        ).as("x")
    ).as("x")
).as("x");
