import * as tsql from "../../../../../../../dist";

export const expr = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            true,
                                                            true
                                                        ),
                                                        true
                                                    ),
                                                    true
                                                ),
                                                true
                                            ),
                                            true
                                        ),
                                        true
                                    ),
                                    true
                                ),
                                true
                            ),
                            true
                        ),
                        true
                    ),
                    true
                ),
                true
            ),
            true
        ),
        true
    ),
    null as unknown as tsql.IColumn<{
        mapper : () => boolean,
        tableAlias : "x",
        columnAlias : "y",
    }>
);
export const expr2 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        expr,
                                                                                        expr
                                                                                    ),
                                                                                    expr
                                                                                ),
                                                                                expr
                                                                            ),
                                                                            expr
                                                                        ),
                                                                        expr
                                                                    ),
                                                                    expr
                                                                ),
                                                                expr
                                                            ),
                                                            expr
                                                        ),
                                                        expr
                                                    ),
                                                    expr
                                                ),
                                                expr
                                            ),
                                            expr
                                        ),
                                        expr
                                    ),
                                    expr
                                ),
                                expr
                            ),
                            expr
                        ),
                        expr
                    ),
                    expr
                ),
                expr
            ),
            expr
        ),
        expr
    ),
    expr
);
export const expr3 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        expr2,
                                                                                        expr2
                                                                                    ),
                                                                                    expr2
                                                                                ),
                                                                                expr2
                                                                            ),
                                                                            expr2
                                                                        ),
                                                                        expr2
                                                                    ),
                                                                    expr2
                                                                ),
                                                                expr2
                                                            ),
                                                            expr2
                                                        ),
                                                        expr2
                                                    ),
                                                    expr2
                                                ),
                                                expr2
                                            ),
                                            expr2
                                        ),
                                        expr2
                                    ),
                                    expr2
                                ),
                                expr2
                            ),
                            expr2
                        ),
                        expr2
                    ),
                    expr2
                ),
                expr2
            ),
            expr2
        ),
        expr2
    ),
    expr2
);
export const expr4 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        expr3,
                                                                                        expr3
                                                                                    ),
                                                                                    expr3
                                                                                ),
                                                                                expr3
                                                                            ),
                                                                            expr3
                                                                        ),
                                                                        expr3
                                                                    ),
                                                                    expr3
                                                                ),
                                                                expr3
                                                            ),
                                                            expr3
                                                        ),
                                                        expr3
                                                    ),
                                                    expr3
                                                ),
                                                expr3
                                            ),
                                            expr3
                                        ),
                                        expr3
                                    ),
                                    expr3
                                ),
                                expr3
                            ),
                            expr3
                        ),
                        expr3
                    ),
                    expr3
                ),
                expr3
            ),
            expr3
        ),
        expr3
    ),
    expr3
);

export const expr5 = tsql.and(
    tsql.and(
        tsql.and(
            tsql.and(
                tsql.and(
                    tsql.and(
                        tsql.and(
                            tsql.and(
                                tsql.and(
                                    tsql.and(
                                        tsql.and(
                                            tsql.and(
                                                tsql.and(
                                                    tsql.and(
                                                        tsql.and(
                                                            tsql.and(
                                                                tsql.and(
                                                                    tsql.and(
                                                                        tsql.and(
                                                                            tsql.and(
                                                                                tsql.and(
                                                                                    tsql.and(
                                                                                        expr4,
                                                                                        expr4
                                                                                    ),
                                                                                    expr4
                                                                                ),
                                                                                expr4
                                                                            ),
                                                                            expr4
                                                                        ),
                                                                        expr4
                                                                    ),
                                                                    expr4
                                                                ),
                                                                expr4
                                                            ),
                                                            expr4
                                                        ),
                                                        expr4
                                                    ),
                                                    expr4
                                                ),
                                                expr4
                                            ),
                                            expr4
                                        ),
                                        expr4
                                    ),
                                    expr4
                                ),
                                expr4
                            ),
                            expr4
                        ),
                        expr4
                    ),
                    expr4
                ),
                expr4
            ),
            expr4
        ),
        expr4
    ),
    expr4
);



/**
 * No more errors after 100+ calls.
 * This is good.
 */
tsql.and(
    expr5,
    expr5
);
