export declare const k: ({
    readonly aa: Date;
    readonly bb: number;
} & Partial<{
    readonly dd: string;
    readonly cc: Buffer;
}>) | ({
    readonly dd: string;
    readonly cc: Buffer;
} & Partial<{
    readonly aa: Date;
    readonly bb: number;
}>) | ({
    readonly dd: string;
    readonly aa: Date;
} & Partial<{
    readonly bb: number;
    readonly cc: Buffer;
}>) | ({
    readonly ee: Date;
    readonly ff: number;
} & Partial<{
    readonly gg: Buffer;
    readonly hh: string;
}>) | ({
    readonly gg: Buffer;
    readonly hh: string;
} & Partial<{
    readonly ee: Date;
    readonly ff: number;
}>) | ({
    readonly ee: Date;
    readonly hh: string;
} & Partial<{
    readonly ff: number;
    readonly gg: Buffer;
}>);
