import * as tsql from "../../../../../dist";
export declare const orderByClause: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause2: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause3: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause4: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause5: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause6: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause7: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause8: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause9: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
export declare const orderByClause10: (readonly [tsql.SortExpr, "ASC" | "DESC"])[];
