import * as tm from "type-mapping/fluent";
import * as tsql from "../../../../../../dist";

const myTable = tsql.table("myTable")
    .addColumns({
        someColumnA : tm.mysql.double(),
        someColumnB : tm.mysql.double(),
        someColumnC : tm.mysql.double(),
    });

export const expr0 = tsql.coalesce(
    myTable.columns.someColumnA,
    myTable.columns.someColumnB,
    myTable.columns.someColumnC,
    tsql.coalesce(
        myTable.columns.someColumnA,
        myTable.columns.someColumnB,
        myTable.columns.someColumnC,
        tsql.coalesce(
            myTable.columns.someColumnA,
            myTable.columns.someColumnB,
            myTable.columns.someColumnC,
            tsql.coalesce(
                myTable.columns.someColumnA,
                myTable.columns.someColumnB,
                myTable.columns.someColumnC,
                tsql.coalesce(
                    myTable.columns.someColumnA,
                    myTable.columns.someColumnB,
                    myTable.columns.someColumnC,
                    tsql.coalesce(
                        myTable.columns.someColumnA,
                        myTable.columns.someColumnB,
                        myTable.columns.someColumnC,
                        tsql.coalesce(
                            myTable.columns.someColumnA,
                            myTable.columns.someColumnB,
                            myTable.columns.someColumnC,
                            tsql.coalesce(
                                myTable.columns.someColumnA,
                                myTable.columns.someColumnB,
                                myTable.columns.someColumnC,
                                tsql.coalesce(
                                    myTable.columns.someColumnA,
                                    myTable.columns.someColumnB,
                                    myTable.columns.someColumnC,
                                    tsql.coalesce(
                                        myTable.columns.someColumnA,
                                        myTable.columns.someColumnB,
                                        myTable.columns.someColumnC,
                                        tsql.coalesce(
                                            myTable.columns.someColumnA,
                                            myTable.columns.someColumnB,
                                            myTable.columns.someColumnC,
                                            tsql.coalesce(
                                                myTable.columns.someColumnA,
                                                myTable.columns.someColumnB,
                                                myTable.columns.someColumnC,
                                                tsql.coalesce(
                                                    myTable.columns.someColumnA,
                                                    myTable.columns.someColumnB,
                                                    myTable.columns.someColumnC,
                                                    tsql.coalesce(
                                                        myTable.columns.someColumnA,
                                                        myTable.columns.someColumnB,
                                                        myTable.columns.someColumnC,
                                                        tsql.coalesce(
                                                            myTable.columns.someColumnA,
                                                            myTable.columns.someColumnB,
                                                            myTable.columns.someColumnC,
                                                            tsql.coalesce(
                                                                myTable.columns.someColumnA,
                                                                myTable.columns.someColumnB,
                                                                myTable.columns.someColumnC,
                                                                tsql.coalesce(
                                                                    myTable.columns.someColumnA,
                                                                    myTable.columns.someColumnB,
                                                                    myTable.columns.someColumnC,
                                                                    tsql.coalesce(
                                                                        myTable.columns.someColumnA,
                                                                        myTable.columns.someColumnB,
                                                                        myTable.columns.someColumnC,
                                                                        tsql.coalesce(
                                                                            myTable.columns.someColumnA,
                                                                            myTable.columns.someColumnB,
                                                                            myTable.columns.someColumnC,
                                                                            tsql.coalesce(
                                                                                tsql.double.acos(
                                                                                    tsql.coalesce(
                                                                                        tsql.double.acos(
                                                                                            tsql.coalesce(
                                                                                                tsql.double.acos(myTable.columns.someColumnC),
                                                                                                myTable.columns.someColumnA,
                                                                                                myTable.columns.someColumnB,
                                                                                                myTable.columns.someColumnC,
                                                                                            )
                                                                                        ),
                                                                                        myTable.columns.someColumnA,
                                                                                        myTable.columns.someColumnB,
                                                                                        myTable.columns.someColumnC,
                                                                                    )
                                                                                ),
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                                myTable.columns.someColumnC,
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);

export const expr1 = tsql.coalesce(
    myTable.columns.someColumnA,
    myTable.columns.someColumnB,
    myTable.columns.someColumnC,
    tsql.coalesce(
        myTable.columns.someColumnA,
        myTable.columns.someColumnB,
        myTable.columns.someColumnC,
        tsql.coalesce(
            myTable.columns.someColumnA,
            myTable.columns.someColumnB,
            myTable.columns.someColumnC,
            tsql.coalesce(
                myTable.columns.someColumnA,
                myTable.columns.someColumnB,
                myTable.columns.someColumnC,
                tsql.coalesce(
                    myTable.columns.someColumnA,
                    myTable.columns.someColumnB,
                    myTable.columns.someColumnC,
                    tsql.coalesce(
                        myTable.columns.someColumnA,
                        myTable.columns.someColumnB,
                        myTable.columns.someColumnC,
                        tsql.coalesce(
                            myTable.columns.someColumnA,
                            myTable.columns.someColumnB,
                            myTable.columns.someColumnC,
                            tsql.coalesce(
                                myTable.columns.someColumnA,
                                myTable.columns.someColumnB,
                                myTable.columns.someColumnC,
                                tsql.coalesce(
                                    myTable.columns.someColumnA,
                                    myTable.columns.someColumnB,
                                    myTable.columns.someColumnC,
                                    tsql.coalesce(
                                        myTable.columns.someColumnA,
                                        myTable.columns.someColumnB,
                                        myTable.columns.someColumnC,
                                        tsql.coalesce(
                                            myTable.columns.someColumnA,
                                            myTable.columns.someColumnB,
                                            myTable.columns.someColumnC,
                                            tsql.coalesce(
                                                myTable.columns.someColumnA,
                                                myTable.columns.someColumnB,
                                                myTable.columns.someColumnC,
                                                tsql.coalesce(
                                                    myTable.columns.someColumnA,
                                                    myTable.columns.someColumnB,
                                                    myTable.columns.someColumnC,
                                                    tsql.coalesce(
                                                        myTable.columns.someColumnA,
                                                        myTable.columns.someColumnB,
                                                        myTable.columns.someColumnC,
                                                        tsql.coalesce(
                                                            myTable.columns.someColumnA,
                                                            myTable.columns.someColumnB,
                                                            myTable.columns.someColumnC,
                                                            tsql.coalesce(
                                                                myTable.columns.someColumnA,
                                                                myTable.columns.someColumnB,
                                                                myTable.columns.someColumnC,
                                                                tsql.coalesce(
                                                                    myTable.columns.someColumnA,
                                                                    myTable.columns.someColumnB,
                                                                    myTable.columns.someColumnC,
                                                                    tsql.coalesce(
                                                                        myTable.columns.someColumnA,
                                                                        myTable.columns.someColumnB,
                                                                        myTable.columns.someColumnC,
                                                                        tsql.coalesce(
                                                                            myTable.columns.someColumnA,
                                                                            myTable.columns.someColumnB,
                                                                            myTable.columns.someColumnC,
                                                                            tsql.coalesce(
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                                myTable.columns.someColumnC,
                                                                                tsql.coalesce(
                                                                                    myTable.columns.someColumnA,
                                                                                    myTable.columns.someColumnB,
                                                                                    myTable.columns.someColumnC,
                                                                                    tsql.coalesce(
                                                                                        myTable.columns.someColumnA,
                                                                                        myTable.columns.someColumnB,
                                                                                        myTable.columns.someColumnC,
                                                                                        expr0
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);

export const expr2 = tsql.coalesce(
    myTable.columns.someColumnA,
    myTable.columns.someColumnB,
    myTable.columns.someColumnC,
    tsql.coalesce(
        myTable.columns.someColumnA,
        myTable.columns.someColumnB,
        myTable.columns.someColumnC,
        tsql.coalesce(
            myTable.columns.someColumnA,
            myTable.columns.someColumnB,
            myTable.columns.someColumnC,
            tsql.coalesce(
                myTable.columns.someColumnA,
                myTable.columns.someColumnB,
                myTable.columns.someColumnC,
                tsql.coalesce(
                    myTable.columns.someColumnA,
                    myTable.columns.someColumnB,
                    myTable.columns.someColumnC,
                    tsql.coalesce(
                        myTable.columns.someColumnA,
                        myTable.columns.someColumnB,
                        myTable.columns.someColumnC,
                        tsql.coalesce(
                            myTable.columns.someColumnA,
                            myTable.columns.someColumnB,
                            myTable.columns.someColumnC,
                            tsql.coalesce(
                                myTable.columns.someColumnA,
                                myTable.columns.someColumnB,
                                myTable.columns.someColumnC,
                                tsql.coalesce(
                                    myTable.columns.someColumnA,
                                    myTable.columns.someColumnB,
                                    myTable.columns.someColumnC,
                                    tsql.coalesce(
                                        myTable.columns.someColumnA,
                                        myTable.columns.someColumnB,
                                        myTable.columns.someColumnC,
                                        tsql.coalesce(
                                            myTable.columns.someColumnA,
                                            myTable.columns.someColumnB,
                                            myTable.columns.someColumnC,
                                            tsql.coalesce(
                                                myTable.columns.someColumnA,
                                                myTable.columns.someColumnB,
                                                myTable.columns.someColumnC,
                                                tsql.coalesce(
                                                    myTable.columns.someColumnA,
                                                    myTable.columns.someColumnB,
                                                    myTable.columns.someColumnC,
                                                    tsql.coalesce(
                                                        myTable.columns.someColumnA,
                                                        myTable.columns.someColumnB,
                                                        myTable.columns.someColumnC,
                                                        tsql.coalesce(
                                                            myTable.columns.someColumnA,
                                                            myTable.columns.someColumnB,
                                                            myTable.columns.someColumnC,
                                                            tsql.coalesce(
                                                                myTable.columns.someColumnA,
                                                                myTable.columns.someColumnB,
                                                                myTable.columns.someColumnC,
                                                                tsql.coalesce(
                                                                    myTable.columns.someColumnA,
                                                                    myTable.columns.someColumnB,
                                                                    myTable.columns.someColumnC,
                                                                    tsql.coalesce(
                                                                        myTable.columns.someColumnA,
                                                                        myTable.columns.someColumnB,
                                                                        myTable.columns.someColumnC,
                                                                        tsql.coalesce(
                                                                            myTable.columns.someColumnA,
                                                                            myTable.columns.someColumnB,
                                                                            myTable.columns.someColumnC,
                                                                            tsql.coalesce(
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                                myTable.columns.someColumnC,
                                                                                tsql.coalesce(
                                                                                    myTable.columns.someColumnA,
                                                                                    myTable.columns.someColumnB,
                                                                                    myTable.columns.someColumnC,
                                                                                    tsql.coalesce(
                                                                                        myTable.columns.someColumnA,
                                                                                        myTable.columns.someColumnB,
                                                                                        myTable.columns.someColumnC,
                                                                                        expr1
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);

export const expr3 = tsql.coalesce(
    myTable.columns.someColumnA,
    myTable.columns.someColumnB,
    myTable.columns.someColumnC,
    tsql.coalesce(
        myTable.columns.someColumnA,
        myTable.columns.someColumnB,
        myTable.columns.someColumnC,
        tsql.coalesce(
            myTable.columns.someColumnA,
            myTable.columns.someColumnB,
            myTable.columns.someColumnC,
            tsql.coalesce(
                myTable.columns.someColumnA,
                myTable.columns.someColumnB,
                myTable.columns.someColumnC,
                tsql.coalesce(
                    myTable.columns.someColumnA,
                    myTable.columns.someColumnB,
                    myTable.columns.someColumnC,
                    tsql.coalesce(
                        myTable.columns.someColumnA,
                        myTable.columns.someColumnB,
                        myTable.columns.someColumnC,
                        tsql.coalesce(
                            myTable.columns.someColumnA,
                            myTable.columns.someColumnB,
                            myTable.columns.someColumnC,
                            tsql.coalesce(
                                myTable.columns.someColumnA,
                                myTable.columns.someColumnB,
                                myTable.columns.someColumnC,
                                tsql.coalesce(
                                    myTable.columns.someColumnA,
                                    myTable.columns.someColumnB,
                                    myTable.columns.someColumnC,
                                    tsql.coalesce(
                                        myTable.columns.someColumnA,
                                        myTable.columns.someColumnB,
                                        myTable.columns.someColumnC,
                                        tsql.coalesce(
                                            myTable.columns.someColumnA,
                                            myTable.columns.someColumnB,
                                            myTable.columns.someColumnC,
                                            tsql.coalesce(
                                                myTable.columns.someColumnA,
                                                myTable.columns.someColumnB,
                                                myTable.columns.someColumnC,
                                                tsql.coalesce(
                                                    myTable.columns.someColumnA,
                                                    myTable.columns.someColumnB,
                                                    myTable.columns.someColumnC,
                                                    tsql.coalesce(
                                                        myTable.columns.someColumnA,
                                                        myTable.columns.someColumnB,
                                                        myTable.columns.someColumnC,
                                                        tsql.coalesce(
                                                            myTable.columns.someColumnA,
                                                            myTable.columns.someColumnB,
                                                            myTable.columns.someColumnC,
                                                            tsql.coalesce(
                                                                myTable.columns.someColumnA,
                                                                myTable.columns.someColumnB,
                                                                myTable.columns.someColumnC,
                                                                tsql.coalesce(
                                                                    myTable.columns.someColumnA,
                                                                    myTable.columns.someColumnB,
                                                                    myTable.columns.someColumnC,
                                                                    tsql.coalesce(
                                                                        myTable.columns.someColumnA,
                                                                        myTable.columns.someColumnB,
                                                                        myTable.columns.someColumnC,
                                                                        tsql.coalesce(
                                                                            myTable.columns.someColumnA,
                                                                            myTable.columns.someColumnB,
                                                                            myTable.columns.someColumnC,
                                                                            tsql.coalesce(
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                                myTable.columns.someColumnC,
                                                                                tsql.coalesce(
                                                                                    myTable.columns.someColumnA,
                                                                                    myTable.columns.someColumnB,
                                                                                    myTable.columns.someColumnC,
                                                                                    tsql.coalesce(
                                                                                        myTable.columns.someColumnA,
                                                                                        myTable.columns.someColumnB,
                                                                                        myTable.columns.someColumnC,
                                                                                        expr2
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);

export const expr4 = tsql.coalesce(
    myTable.columns.someColumnA,
    myTable.columns.someColumnB,
    myTable.columns.someColumnC,
    tsql.coalesce(
        myTable.columns.someColumnA,
        myTable.columns.someColumnB,
        myTable.columns.someColumnC,
        tsql.coalesce(
            myTable.columns.someColumnA,
            myTable.columns.someColumnB,
            myTable.columns.someColumnC,
            tsql.coalesce(
                myTable.columns.someColumnA,
                myTable.columns.someColumnB,
                myTable.columns.someColumnC,
                tsql.coalesce(
                    myTable.columns.someColumnA,
                    myTable.columns.someColumnB,
                    myTable.columns.someColumnC,
                    tsql.coalesce(
                        myTable.columns.someColumnA,
                        myTable.columns.someColumnB,
                        myTable.columns.someColumnC,
                        tsql.coalesce(
                            myTable.columns.someColumnA,
                            myTable.columns.someColumnB,
                            myTable.columns.someColumnC,
                            tsql.coalesce(
                                myTable.columns.someColumnA,
                                myTable.columns.someColumnB,
                                myTable.columns.someColumnC,
                                tsql.coalesce(
                                    myTable.columns.someColumnA,
                                    myTable.columns.someColumnB,
                                    myTable.columns.someColumnC,
                                    tsql.coalesce(
                                        myTable.columns.someColumnA,
                                        myTable.columns.someColumnB,
                                        myTable.columns.someColumnC,
                                        tsql.coalesce(
                                            myTable.columns.someColumnA,
                                            myTable.columns.someColumnB,
                                            myTable.columns.someColumnC,
                                            tsql.coalesce(
                                                myTable.columns.someColumnA,
                                                myTable.columns.someColumnB,
                                                myTable.columns.someColumnC,
                                                tsql.coalesce(
                                                    myTable.columns.someColumnA,
                                                    myTable.columns.someColumnB,
                                                    myTable.columns.someColumnC,
                                                    tsql.coalesce(
                                                        myTable.columns.someColumnA,
                                                        myTable.columns.someColumnB,
                                                        myTable.columns.someColumnC,
                                                        tsql.coalesce(
                                                            myTable.columns.someColumnA,
                                                            myTable.columns.someColumnB,
                                                            myTable.columns.someColumnC,
                                                            tsql.coalesce(
                                                                myTable.columns.someColumnA,
                                                                myTable.columns.someColumnB,
                                                                myTable.columns.someColumnC,
                                                                tsql.coalesce(
                                                                    myTable.columns.someColumnA,
                                                                    myTable.columns.someColumnB,
                                                                    myTable.columns.someColumnC,
                                                                    tsql.coalesce(
                                                                        myTable.columns.someColumnA,
                                                                        myTable.columns.someColumnB,
                                                                        myTable.columns.someColumnC,
                                                                        tsql.coalesce(
                                                                            myTable.columns.someColumnA,
                                                                            myTable.columns.someColumnB,
                                                                            myTable.columns.someColumnC,
                                                                            tsql.coalesce(
                                                                                myTable.columns.someColumnA,
                                                                                myTable.columns.someColumnB,
                                                                                myTable.columns.someColumnC,
                                                                                tsql.coalesce(
                                                                                    myTable.columns.someColumnA,
                                                                                    myTable.columns.someColumnB,
                                                                                    myTable.columns.someColumnC,
                                                                                    tsql.coalesce(
                                                                                        myTable.columns.someColumnA,
                                                                                        myTable.columns.someColumnB,
                                                                                        myTable.columns.someColumnC,
                                                                                        expr3
                                                                                    )
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);
